export const UPDATE_INPUT_FIELD = 'UPDATE_INPUT_FIELD';

export const AJAX_CALL_HAS_ERROR = 'AJAX_CALL_HAS_ERROR';
export const AJAX_CALL_IS_LOADING = 'AJAX_CALL_IS_LOADING';
export const FETCH_POKEMON_DATA_SUCCESS = 'FETCH_POKEMON_DATA_SUCCESS';